# -*- encoding: utf-8 -*-
"""
定义数据库模型实体 
"""
from sqlalchemy import Column, Integer, String, Float, DateTime, func, Index, Date, SmallInteger, Text
from model.util import Base

class CrawlForexExchange(Base):
    """行情资讯类"""
    __tablename__ = 'jujin8_forex_exchange'

    id = Column(Integer, primary_key=True)
    abstractInfo = Column(String(512))
    applyId = Column(Integer)
    applyTime = Column(String(32))
    ascribe = Column(String(36))
    biggestLeverage = Column(String(64))
    cName = Column(String(32))
    checkOrNot = Column(String(32))
    checkedPass = Column(String(8))
    checkedStatus = Column(String(32))
    companyName = Column(String(128))
    condition = Column(String(128))
    createTime = Column(String(32))
    degreeOfPraise = Column(String(32))
    depositMethod = Column(String(64))
    eName = Column(String(64))
    eaDeal = Column(String(64))
    establishTime = Column(String(32))
    gold = Column(String(32))
    hedge = Column(SmallInteger)
    homeCountry = Column(String(128))
    source_id = Column(Integer)
    ids = Column(String(64))
    intro = Column(String(512))
    licenseNo = Column(String(64))
    likeCount = Column(Integer)
    mainSpread = Column(String(64))
    maxSpread = Column(String(64))
    forexExchangeCommission = Column(String(64))
    minSpread = Column(String(64))
    officialBankAddress = Column(String(256))
    officialWebsite = Column(String(256))
    orgLicense = Column(String(64))
    platformLogo = Column(String(128))
    platName = Column(String(64))
    platStatus = Column(String(64))
    platformIcon = Column(String(256))
    platformStatus = Column(String(256))
    platformType = Column(String(64))
    recommendOrNot = Column(String(16))
    relevancy = Column(String(64))
    scalp = Column(String(64))
    show = Column(SmallInteger)
    showPlatform = Column(SmallInteger)
    softwareInfo = Column(String(128))
    sortNo = Column(Integer)
    source = Column(String(64))
    spreadInfo = Column(String(64))
    supervisionOrg = Column(String(128))
    supervisionOrgName = Column(String(64))
    surveyType = Column(String(64))
    swap = Column(String(64))
    synthesisScore = Column(String(64))
    tradeVariety = Column(String(64))
    tradingModel = Column(String(64))
    trailingStop = Column(String(64))
    withdrawMethod = Column(String(64))

    created_at = Column(DateTime, default=func.now())
    updated_at = Column(DateTime, default=func.now(), onupdate=func.now())